# Generated by Django 4.0.6 on 2022-07-20 19:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('link_lusofona', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('ects', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('ano_letivo_freq', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(regex='\\d\\d\\d\\d\\/\\d\\d')])),
                ('topicos', models.TextField(max_length=300)),
                ('ranking', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('link_pagina', models.TextField(blank=True, max_length=300)),
                ('feita', models.BooleanField(default=False)),
                ('professores', models.ManyToManyField(related_name='cadeiras', to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='portfolio.unidadecurricular')),
            ],
        ),
    ]
