# Generated by Django 4.0.6 on 2022-07-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_artigomedium_blog_competencia_formacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='competencias',
            field=models.ManyToManyField(related_name='projetos', to='portfolio.competencia'),
        ),
    ]
