# Generated by Django 4.0.6 on 2022-07-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projeto_competencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacao',
            name='link_instituicao',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
