# Generated by Django 4.0.6 on 2022-07-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_formacao_link_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacao',
            name='ano_inicio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formacao',
            name='local',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
