# Generated by Django 4.0.6 on 2022-07-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_data_pub_blog_datahora_blog_imagem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogPost',
        ),
    ]
