# Generated by Django 4.0.6 on 2022-07-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_blogpost_datahora'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('link_artigo', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='ArtigoMedium',
        ),
        migrations.RemoveField(
            model_name='trabalhofinalcurso',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='trabalhofinalcurso',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='trabalhofinalcurso',
            name='orientador',
        ),
        migrations.AddField(
            model_name='trabalhofinalcurso',
            name='ano_realizado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabalhofinalcurso',
            name='autores',
            field=models.ManyToManyField(related_name='autor_tfc', to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='trabalhofinalcurso',
            name='orientadores',
            field=models.ManyToManyField(related_name='orientador_tfc', to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='trabalhofinalcurso',
            name='sumario',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trabalhofinalcurso',
            name='link_github',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='trabalhofinalcurso',
            name='link_youtube',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='trabalhofinalcurso',
            name='resumo',
            field=models.TextField(max_length=500),
        ),
    ]
