# Generated by Django 4.0.6 on 2022-07-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_noticiamedium_delete_artigomedium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='tipo_tecnologia',
            field=models.CharField(choices=[('F', 'Front-end'), ('B', 'Back-end'), ('O', 'Outras')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='usada_projeto',
            field=models.BooleanField(default=False),
        ),
    ]
