# Generated by Django 4.0.6 on 2022-07-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_tecnologia_tipo_tecnologia_tecnologia_usada_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologia',
            name='contexto_usado',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
