# Generated by Django 4.0.6 on 2022-07-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_tecnologia_contexto_usado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologia',
            name='acronimo',
            field=models.CharField(max_length=10),
        ),
    ]
