# Generated by Django 4.0.6 on 2022-07-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_tecnologia_acronimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologia',
            name='tipo_tecnologia',
            field=models.CharField(choices=[('F', 'Front-end'), ('B', 'Back-end'), ('O', 'Outras'), ('P', 'Linguagem de Programação')], default='O', max_length=1),
        ),
    ]
