# Generated by Django 4.0.6 on 2022-07-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_tecnologia_tipo_tecnologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhofinalcurso',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
