# Generated by Django 4.0.6 on 2022-07-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_blogpost_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticiaMedium',
        ),
    ]
